name: CI

# Controls when the action will run. 
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - '**'
    types: [ opened, edited, synchronize ]

jobs:
  build:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v2
    - name: CocoaPods
      run: |
        gem install xcpretty -N
        make init
    - name: Force xcode 12
      run: |
        sudo xcode-select -switch /Applications/Xcode_12.app
    - name: Build
      run: |
        make build
    - name: Package Build
      run: |
        swift build -Xswiftc "-sdk" -Xswiftc "`xcrun --sdk iphonesimulator --show-sdk-path`" -Xswiftc "-target" -Xswiftc "x86_64-apple-ios12.1-simulator" -Xswiftc "-lswiftUIKit"
    - name: Example Build
      run: |
        make example_build
